import os

ROOT_DIR = os.path.dirname(os.path.abspath(__file__)) # This is your Project Root


DATA_DIR = ROOT_DIR + "/data"
RAW_DATA_DIR = DATA_DIR + "/raw"

PERIOD_START_EVENT_MSG_TYPE = 12
PERIOD_START_ACTION_TYPE = 0

SUBSTITUTE_EVENT_MSG_TYPE = 8

MADE_BASKET_EVENT_MSG_TYPE = 1
MISSED_BASKET_EVENT_MSG_TYPE = 2

REBOUND_EVENT_MSG_TYPE = 4
